env_defaults:
  db_host: localhost
  db_name: "{{ site | underscore }}_{{ env }}"
  db_user: "{{ site | underscore }}"
  domain_current_site: "{{ project.site_hosts | map(attribute='canonical') | first }}"
  git_sha: "{{ git_clone.after }}"
  release_version: "{{ deploy_helper.new_release }}"

site_env: "{{ env_defaults | combine(vault_env_defaults | default({}), project.env | default({}), vault_sites[site].env) }}"
