# Documentation: https://roots.io/trellis/docs/troubleshooting/#composer-install-host-key-verification-failed

# Host keys to add to known_hosts
known_hosts: []

# Whether to automatically accept the host key for your `repo` (in `sites`) during git clone.
# To avoid man-in-the-middle attacks, set this to `false` and add repo host key to `known_hosts` above.
repo_accept_hostkey: true
