---
- name: disable temporary challenge sites
  import_tasks: disable_challenge_sites.yml

- name: reload php-fpm
  service:
    name: php7.4-fpm
    state: reloaded

- import_tasks: reload_nginx.yml
