---
- name: Install required packages to install PHP 7.3
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - lsb-release
    - ca-certificates

- name: Add PHP 7.3 APT key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    keyring: /etc/apt/trusted.gpg.d/php.gpg

- name: Add PHP 7.3 APT repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    filename: php
    update_cache: yes

- name: Install PHP 7.3
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_dict: "{{ php_extensions }}"

- name: Start php7.3-fpm service
  service:
    name: php7.3-fpm
    state: started
    enabled: true

- name: Check for existing php7.2-fpm service
  stat:
    path: /etc/init.d/php7.2-fpm
  register: php72_status

- name: Stop php7.2-fpm service if it exists
  service:
    name: php7.2-fpm
    state: stopped
    enabled: false
  register: service_stopped
  when: php72_status.stat.exists
  notify: reload php-fpm

- name: PHP configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/7.3/fpm/php.ini
  notify: reload php-fpm
